version: "3"

services:
  web:
    image: cr.yandex/crp6nr6apjkfmjnr553u/ex-py:1.0.0
    env_file:
      - web.env
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
        backend:
          ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    env_file:
      - db.env
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql/
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10

  reverse-proxy:
    image: haproxy
    volumes:
    - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw 
    ports:
    - "8080:8080"
    restart: always
    networks:
        backend:
          ipv4_address: 172.20.0.15

  ingress-proxy:
    image: nginx:latest
    volumes:
    - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw
    ports:
    - "8090:8090"
    restart: always
    networks:
        backend:
          ipv4_address: 172.20.0.20

networks:
  backend:
    driver: bridge
    ipam:
     config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1
